const GITHUB_URL = "https://github.com/l3chat/telegram-md-bot";

const PAGES = {
  en: {
    title: "Telegram Rich Message — Test Page",
    intro: "This page demonstrates the main formatting features supported by the bot.",
    headings: "Headings",
    lists: "Lists",
    quote: "Quote",
    table: "Table",
    code: "Code",
    math: "Math",
    details: "Expandable section",
    media: "Media syntax",
    end: "End of test",
    para: "Normal paragraph with **bold**, *italic*, ~~strikethrough~~ and `inline code`.",
    bullets: ["first item", "second item", "third item"],
    ordered: ["one", "two", "three"],
    h3: "Level 3 heading",
    h4: "Level 4 heading",
    tableHead: ["Test", "✓"],
    tableRows: [["Markdown", "✓"], ["Table", "✓"], ["Media", "✓"]],
    sourceViewLabel: "View tutorial source",
    sourceRawLabel: "Raw Markdown",
    tasks: ["Markdown", "tables", "code", "media support"],
    quoteText: "Rich Messages can combine structured text, code, tables and media in one Telegram message.",
    detailsText: "This text is inside an expandable section.",
    mediaText: "For real media, send files first and then reference their names in Markdown. Example syntax:",
    footer: "Built with **GPT-6.1**.",
  },
  ru: {
    title: "Telegram Rich Message — тестовая страница",
    intro: "Эта страница демонстрирует основные возможности форматирования, поддерживаемые ботом.",
    headings: "Заголовки",
    lists: "Списки",
    quote: "Цитата",
    table: "Таблица",
    code: "Код",
    math: "Математика",
    details: "Сворачиваемый раздел",
    media: "Синтаксис медиа",
    end: "Конец теста",
    para: "Обычный абзац с **жирным**, *курсивом*, ~~зачёркиванием~~ и `inline code`.",
    bullets: ["первый пункт", "второй пункт", "третий пункт"],
    ordered: ["один", "два", "три"],
    h3: "Заголовок третьего уровня",
    h4: "Заголовок четвёртого уровня",
    tableHead: ["Тест", "✓"],
    tableRows: [["Markdown", "✓"], ["Таблица", "✓"], ["Медиа", "✓"]],
    sourceViewLabel: "Открыть исходник tutorial",
    sourceRawLabel: "Raw Markdown",
    tasks: ["Markdown", "таблицы", "код", "поддержка медиа"],
    quoteText: "Rich Message позволяет объединить структурированный текст, код, таблицы и медиа в одном сообщении Telegram.",
    detailsText: "Этот текст находится внутри сворачиваемого раздела.",
    mediaText: "Для реальных медиа сначала пришлите файлы, затем укажите их имена в Markdown. Пример синтаксиса:",
    footer: "Бот создан с помощью **GPT-6.1**.",
  },
  de: {
    title: "Telegram Rich Message — Testseite",
    intro: "Diese Seite demonstriert die wichtigsten Formatierungsfunktionen des Bots.",
    headings: "Überschriften",
    lists: "Listen",
    quote: "Zitat",
    table: "Tabelle",
    code: "Code",
    math: "Mathematik",
    details: "Aufklappbarer Abschnitt",
    media: "Mediensyntax",
    end: "Ende des Tests",
    para: "Normaler Absatz mit **Fettdruck**, *Kursivschrift*, ~~Durchstreichung~~ und `Inline-Code`.",
    bullets: ["erster Punkt", "zweiter Punkt", "dritter Punkt"],
    ordered: ["eins", "zwei", "drei"],
    h3: "Überschrift Ebene 3",
    h4: "Überschrift Ebene 4",
    tableHead: ["Test", "✓"],
    tableRows: [["Markdown", "✓"], ["Tabelle", "✓"], ["Medien", "✓"]],
    sourceViewLabel: "Tutorial-Quelltext ansehen",
    sourceRawLabel: "Raw Markdown",
    tasks: ["Markdown", "Tabellen", "Code", "Medienunterstützung"],
    quoteText: "Rich Messages können strukturierten Text, Code, Tabellen und Medien in einer Telegram-Nachricht kombinieren.",
    detailsText: "Dieser Text befindet sich in einem aufklappbaren Abschnitt.",
    mediaText: "Für echte Medien zuerst Dateien senden und anschließend ihre Namen im Markdown referenzieren. Beispiel:",
    footer: "Erstellt mit **GPT-6.1**.",
  },
  fr: {
    title: "Telegram Rich Message — Page de test",
    intro: "Cette page présente les principales fonctions de mise en forme prises en charge par le bot.",
    headings: "Titres",
    lists: "Listes",
    quote: "Citation",
    table: "Tableau",
    code: "Code",
    math: "Mathématiques",
    details: "Section repliable",
    media: "Syntaxe des médias",
    end: "Fin du test",
    para: "Paragraphe normal avec **gras**, *italique*, ~~barré~~ et `code inline`.",
    bullets: ["premier élément", "deuxième élément", "troisième élément"],
    ordered: ["un", "deux", "trois"],
    h3: "Titre niveau 3",
    h4: "Titre niveau 4",
    tableHead: ["Test", "✓"],
    tableRows: [["Markdown", "✓"], ["Tableau", "✓"], ["Médias", "✓"]],
    sourceViewLabel: "Voir la source du tutoriel",
    sourceRawLabel: "Markdown brut",
    tasks: ["Markdown", "tableaux", "code", "prise en charge des médias"],
    quoteText: "Les Rich Messages peuvent réunir texte structuré, code, tableaux et médias dans un seul message Telegram.",
    detailsText: "Ce texte se trouve dans une section repliable.",
    mediaText: "Pour de vrais médias, envoyez d’abord les fichiers puis référencez leurs noms dans Markdown. Exemple :",
    footer: "Créé avec **GPT-6.1**.",
  },
  uk: {
    title: "Telegram Rich Message — тестова сторінка",
    intro: "Ця сторінка демонструє основні можливості форматування, які підтримує бот.",
    headings: "Заголовки",
    lists: "Списки",
    quote: "Цитата",
    table: "Таблиця",
    code: "Код",
    math: "Математика",
    details: "Розгортаний розділ",
    media: "Синтаксис медіа",
    end: "Кінець тесту",
    para: "Звичайний абзац із **жирним**, *курсивом*, ~~закресленням~~ та `inline code`.",
    bullets: ["перший пункт", "другий пункт", "третій пункт"],
    ordered: ["один", "два", "три"],
    h3: "Заголовок третього рівня",
    h4: "Заголовок четвертого рівня",
    tableHead: ["Тест", "✓"],
    tableRows: [["Markdown", "✓"], ["Таблиця", "✓"], ["Медіа", "✓"]],
    sourceViewLabel: "Відкрити вихідний tutorial",
    sourceRawLabel: "Raw Markdown",
    tasks: ["Markdown", "таблиці", "код", "підтримка медіа"],
    quoteText: "Rich Message дає змогу поєднати структурований текст, код, таблиці й медіа в одному повідомленні Telegram.",
    detailsText: "Цей текст знаходиться всередині розгортаного розділу.",
    mediaText: "Для справжніх медіа спочатку надішліть файли, а потім укажіть їхні назви в Markdown. Приклад:",
    footer: "Бот створено за допомогою **GPT-6.1**.",
  },
};

function testPageLocale(value) {
  const code = String(value || "").toLowerCase().split(/[-_]/)[0];
  return PAGES[code] ? code : "en";
}

function tutorialViewUrl(locale) {
  const lang = testPageLocale(locale);
  return (
    "https://github.com/l3chat/telegram-md-bot/blob/main/" +
    "docs/tutorial/test-page." +
    lang +
    ".md"
  );
}

function tutorialSourceUrl(locale) {
  const lang = testPageLocale(locale);
  return (
    "https://raw.githubusercontent.com/l3chat/telegram-md-bot/main/" +
    "docs/tutorial/test-page." +
    lang +
    ".md"
  );
}

function testPageMarkdown(locale) {
  const p = PAGES[testPageLocale(locale)];
  return [
    "# " + p.title,
    "",
    p.intro,
    "",
    p.para,
    "",
    "---",
    "",
    "## 1. " + p.headings,
    "",
    "### " + p.h3,
    "",
    "#### " + p.h4,
    "",
    "## 2. " + p.lists,
    "",
    "- " + p.bullets[0],
    "- " + p.bullets[1],
    "- " + p.bullets[2],
    "",
    "1. " + p.ordered[0],
    "2. " + p.ordered[1],
    "3. " + p.ordered[2],
    "",
    "- [x] " + p.tasks[0],
    "- [x] " + p.tasks[1],
    "- [x] " + p.tasks[2],
    "- [ ] " + p.tasks[3],
    "",
    "## 3. " + p.quote,
    "",
    "> " + p.quoteText,
    "",
    "## 4. " + p.table,
    "",
    "|" + p.tableHead[0] + "|" + p.tableHead[1] + "|",
    "|---|---|",
    "|" + p.tableRows[0][0] + "|" + p.tableRows[0][1] + "|",
    "|" + p.tableRows[1][0] + "|" + p.tableRows[1][1] + "|",
    "|" + p.tableRows[2][0] + "|" + p.tableRows[2][1] + "|",
    "",
    "## 5. " + p.code,
    "",
    "```python",
    "def rich_message(name):",
    "    return f\"Hello, {name}!\"",
    "",
    "print(rich_message(\"Telegram\"))",
    "```",
    "",
    "## 6. " + p.math,
    "",
    "$$",
    "f(n)=n^2+n+41",
    "$$",
    "",
    "$$",
    "\\int_{-\\infty}^{\\infty} \\frac{1}{\\sqrt{2\\pi}} e^{-x^2/2}\\,dx = 1",
    "$$",
    "",
    "## 7. " + p.details,
    "",
    "<details>",
    "<summary>" + p.details + "</summary>",
    "",
    p.detailsText,
    "",
    "- A",
    "- B",
    "- C",
    "",
    "</details>",
    "",
    "## 8. " + p.media,
    "",
    p.mediaText,
    "",
    "```md",
    '![](184273.png "Image")',
    '![](ding-dong-01.mp3 "Audio")',
    '![](numbers-01.mp4 "Video")',
    "```",
    "",
    "---",
    "",
    "# " + p.end,
    "",
    p.footer,
    "",
    "[" + p.sourceViewLabel + "](" + tutorialViewUrl(locale) + ")",
    "",
    "[" + p.sourceRawLabel + "](" + tutorialSourceUrl(locale) + ")",
    "",
    "[GitHub](" + GITHUB_URL + ")",
  ].join("\n");
}

export {
  GITHUB_URL,
  PAGES,
  testPageLocale,
  tutorialViewUrl,
  tutorialSourceUrl,
  testPageMarkdown,
};
