const GITHUB_URL = "https://github.com/l3chat/telegram-md-bot";

const PAGES = {
  en: {
    title: "Telegram Rich Message — Test Page",
    intro: "This page demonstrates the main formatting features supported by the bot.",
    headings: "Headings",
    lists: "Lists",
    quote: "Quote",
    table: "Table",
    code: "Code",
    math: "Math",
    details: "Expandable section",
    media: "Media syntax",
    end: "End of test",
    para: "Normal paragraph with **bold**, *italic*, ~~strikethrough~~ and `inline code`.",
    bullets: ["first item", "second item", "third item"],
    tasks: ["Markdown", "tables", "code", "media support"],
    quoteText: "Rich Messages can combine structured text, code, tables and media in one Telegram message.",
    detailsText: "This text is inside an expandable section.",
    mediaText: "For real media, send files first and then reference their names in Markdown. Example syntax:",
    footer: "Built with **GPT-6.1**.",
  },
  ru: {
    title: "Telegram Rich Message — тестовая страница",
    intro: "Эта страница демонстрирует основные возможности форматирования, поддерживаемые ботом.",
    headings: "Заголовки",
    lists: "Списки",
    quote: "Цитата",
    table: "Таблица",
    code: "Код",
    math: "Математика",
    details: "Сворачиваемый раздел",
    media: "Синтаксис медиа",
    end: "Конец теста",
    para: "Обычный абзац с **жирным**, *курсивом*, ~~зачёркиванием~~ и `inline code`.",
    bullets: ["первый пункт", "второй пункт", "третий пункт"],
    tasks: ["Markdown", "таблицы", "код", "поддержка медиа"],
    quoteText: "Rich Message позволяет объединить структурированный текст, код, таблицы и медиа в одном сообщении Telegram.",
    detailsText: "Этот текст находится внутри сворачиваемого раздела.",
    mediaText: "Для реальных медиа сначала пришлите файлы, затем укажите их имена в Markdown. Пример синтаксиса:",
    footer: "Бот создан с помощью **GPT-6.1**.",
  },
  de: {
    title: "Telegram Rich Message — Testseite",
    intro: "Diese Seite demonstriert die wichtigsten Formatierungsfunktionen des Bots.",
    headings: "Überschriften",
    lists: "Listen",
    quote: "Zitat",
    table: "Tabelle",
    code: "Code",
    math: "Mathematik",
    details: "Aufklappbarer Abschnitt",
    media: "Mediensyntax",
    end: "Ende des Tests",
    para: "Normaler Absatz mit **Fettdruck**, *Kursivschrift*, ~~Durchstreichung~~ und `Inline-Code`.",
    bullets: ["erster Punkt", "zweiter Punkt", "dritter Punkt"],
    tasks: ["Markdown", "Tabellen", "Code", "Medienunterstützung"],
    quoteText: "Rich Messages können strukturierten Text, Code, Tabellen und Medien in einer Telegram-Nachricht kombinieren.",
    detailsText: "Dieser Text befindet sich in einem aufklappbaren Abschnitt.",
    mediaText: "Für echte Medien zuerst Dateien senden und anschließend ihre Namen im Markdown referenzieren. Beispiel:",
    footer: "Erstellt mit **GPT-6.1**.",
  },
  fr: {
    title: "Telegram Rich Message — Page de test",
    intro: "Cette page présente les principales fonctions de mise en forme prises en charge par le bot.",
    headings: "Titres",
    lists: "Listes",
    quote: "Citation",
    table: "Tableau",
    code: "Code",
    math: "Mathématiques",
    details: "Section repliable",
    media: "Syntaxe des médias",
    end: "Fin du test",
    para: "Paragraphe normal avec **gras**, *italique*, ~~barré~~ et `code inline`.",
    bullets: ["premier élément", "deuxième élément", "troisième élément"],
    tasks: ["Markdown", "tableaux", "code", "prise en charge des médias"],
    quoteText: "Les Rich Messages peuvent réunir texte structuré, code, tableaux et médias dans un seul message Telegram.",
    detailsText: "Ce texte se trouve dans une section repliable.",
    mediaText: "Pour de vrais médias, envoyez d’abord les fichiers puis référencez leurs noms dans Markdown. Exemple :",
    footer: "Créé avec **GPT-6.1**.",
  },
  uk: {
    title: "Telegram Rich Message — тестова сторінка",
    intro: "Ця сторінка демонструє основні можливості форматування, які підтримує бот.",
    headings: "Заголовки",
    lists: "Списки",
    quote: "Цитата",
    table: "Таблиця",
    code: "Код",
    math: "Математика",
    details: "Розгортаний розділ",
    media: "Синтаксис медіа",
    end: "Кінець тесту",
    para: "Звичайний абзац із **жирним**, *курсивом*, ~~закресленням~~ та `inline code`.",
    bullets: ["перший пункт", "другий пункт", "третій пункт"],
    tasks: ["Markdown", "таблиці", "код", "підтримка медіа"],
    quoteText: "Rich Message дає змогу поєднати структурований текст, код, таблиці й медіа в одному повідомленні Telegram.",
    detailsText: "Цей текст знаходиться всередині розгортаного розділу.",
    mediaText: "Для справжніх медіа спочатку надішліть файли, а потім укажіть їхні назви в Markdown. Приклад:",
    footer: "Бот створено за допомогою **GPT-6.1**.",
  },
};

function testPageLocale(value) {
  const code = String(value || "").toLowerCase().split(/[-_]/)[0];
  return PAGES[code] ? code : "en";
}

function testPageMarkdown(locale) {
  const p = PAGES[testPageLocale(locale)];
  return [
    "# " + p.title,
    "",
    p.intro,
    "",
    p.para,
    "",
    "---",
    "",
    "## 1. " + p.headings,
    "",
    "### H3",
    "",
    "#### H4",
    "",
    "## 2. " + p.lists,
    "",
    "- " + p.bullets[0],
    "- " + p.bullets[1],
    "- " + p.bullets[2],
    "",
    "1. one",
    "2. two",
    "3. three",
    "",
    "- [x] " + p.tasks[0],
    "- [x] " + p.tasks[1],
    "- [x] " + p.tasks[2],
    "- [ ] " + p.tasks[3],
    "",
    "## 3. " + p.quote,
    "",
    "> " + p.quoteText,
    "",
    "## 4. " + p.table,
    "",
    "| Feature | Status |",
    "|---|:---:|",
    "| Markdown | ✅ |",
    "| Tables | ✅ |",
    "| Code | ✅ |",
    "| Media | ✅ |",
    "",
    "## 5. " + p.code,
    "",
    "```python",
    "def rich_message(name):",
    "    return f\"Hello, {name}!\"",
    "",
    "print(rich_message(\"Telegram\"))",
    "```",
    "",
    "## 6. " + p.math,
    "",
    "$$",
    "f(n)=n^2+n+41",
    "$$",
    "",
    "## 7. " + p.details,
    "",
    "<details>",
    "<summary>" + p.details + "</summary>",
    "",
    p.detailsText,
    "",
    "- A",
    "- B",
    "- C",
    "",
    "</details>",
    "",
    "## 8. " + p.media,
    "",
    p.mediaText,
    "",
    "```md",
    '![](photo.jpg "Photo")',
    '![](sample.mp3 "Audio")',
    "```",
    "",
    "---",
    "",
    "# " + p.end,
    "",
    p.footer,
    "",
    "[GitHub](" + GITHUB_URL + ")",
  ].join("\n");
}

export {
  GITHUB_URL,
  PAGES,
  testPageLocale,
  testPageMarkdown,
};
